/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package janken;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;

/**
 *
 * @author marukawadaiki
 */
public class ComputerPlayerFrame extends javax.swing.JFrame {
    private ComputerPlayer player = null;
    private Image[] handImage = null;
    private JCanvas c = null;

    /**
     * Creates new form NewJFrame
     */
    public ComputerPlayerFrame(ComputerPlayer p) {
        initComponents();
        player=p;
        setTitle(p.getNameId());
        
        c=new JCanvas();
        handImagePanel.setLayout(new BorderLayout());
        handImagePanel.add(c);
        c.setPreferredSize(new Dimension(100,100));
        c.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PonButton = new javax.swing.JButton();
        HandLabel = new javax.swing.JLabel();
        handImagePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PonButton.setText("Pon");
        PonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PonButtonActionPerformed(evt);
            }
        });

        HandLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        HandLabel.setText("まだだよ");

        javax.swing.GroupLayout handImagePanelLayout = new javax.swing.GroupLayout(handImagePanel);
        handImagePanel.setLayout(handImagePanelLayout);
        handImagePanelLayout.setHorizontalGroup(
            handImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        handImagePanelLayout.setVerticalGroup(
            handImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(PonButton)
                .addGap(28, 28, 28)
                .addComponent(HandLabel)
                .addGap(18, 18, 18)
                .addComponent(handImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PonButton)
                    .addComponent(HandLabel))
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(handImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PonButtonActionPerformed
        // TODO add your handling code here:
        pon();
    }//GEN-LAST:event_PonButtonActionPerformed

    public void pon(){
        int hand = player.pon();
        HandLabel.setText(ComputerPlayer.toStringHand(hand));
        c.setHand(hand);
        c.repaint();
    }
    
    /**/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HandLabel;
    private javax.swing.JButton PonButton;
    private javax.swing.JPanel handImagePanel;
    // End of variables declaration//GEN-END:variables
}
