/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janken;

import java.awt.BorderLayout;
import java.awt.Dimension;

import java.awt.Image;

/**
 *
 * @author marukawadaiki
 */
public class HumanPlayerFrame extends javax.swing.JFrame {

    private HumanPlayer player = null;
    private MatchFrame matchFrame = null;
    private Image[] handImage = null;
    private JCanvas c = null;

    /**
     * Creates new form NewJFrame
     */
    public HumanPlayerFrame(HumanPlayer p) {
        initComponents();
        player = p;
        setTitle(p.getNameId());

        c = new JCanvas();
        handImagePanel.setLayout(new BorderLayout());
        handImagePanel.add(c);
        c.setPreferredSize(new Dimension(100, 100));
        c.repaint();

    }
    public void setMatchFrame(MatchFrame mf){
        matchFrame = mf;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guuButton = new javax.swing.JButton();
        HandLabel = new javax.swing.JLabel();
        handImagePanel = new javax.swing.JPanel();
        chokiButton = new javax.swing.JButton();
        paaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guuButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        guuButton.setText("ぐー");
        guuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guuButtonActionPerformed(evt);
            }
        });

        HandLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        HandLabel.setText("まだだよ");

        javax.swing.GroupLayout handImagePanelLayout = new javax.swing.GroupLayout(handImagePanel);
        handImagePanel.setLayout(handImagePanelLayout);
        handImagePanelLayout.setHorizontalGroup(
            handImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        handImagePanelLayout.setVerticalGroup(
            handImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        chokiButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        chokiButton.setText("ちょき");
        chokiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chokiButtonActionPerformed(evt);
            }
        });

        paaButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        paaButton.setText("ぱー");
        paaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guuButton)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HandLabel)
                            .addComponent(chokiButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(handImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(paaButton)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guuButton)
                    .addComponent(chokiButton)
                    .addComponent(paaButton))
                .addGap(18, 18, 18)
                .addComponent(HandLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(handImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewUpdate(int hand) {
        HandLabel.setText(ComputerPlayer.toStringHand(hand));
        c.setHand(hand);
        c.repaint();
    }

    private void guuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guuButtonActionPerformed
        // TODO add your handling code here:
        player.pon(0);
        matchFrame.pon();
        viewUpdate(0);
    }//GEN-LAST:event_guuButtonActionPerformed

    private void chokiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chokiButtonActionPerformed
        // TODO add your handling code here:
        player.pon(1);
        matchFrame.pon();
        viewUpdate(1);
    }//GEN-LAST:event_chokiButtonActionPerformed

    private void paaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paaButtonActionPerformed
        // TODO add your handling code here:
        player.pon(2);
        matchFrame.pon();
        viewUpdate(2);
    }//GEN-LAST:event_paaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HandLabel;
    private javax.swing.JButton chokiButton;
    private javax.swing.JButton guuButton;
    private javax.swing.JPanel handImagePanel;
    private javax.swing.JButton paaButton;
    // End of variables declaration//GEN-END:variables
}
