/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package janken;

/**
 *
 * @author marukawadaiki
 */
public class MatchFrame extends javax.swing.JFrame {
    private Match match = null;
    
    private HumanPlayerFrame playerFrame1 = null;
    private ComputerPlayerFrame playerFrame2 = null;
    
    /**
     * Creates new form MatchFrame
     */
    public MatchFrame(Match m) {
        initComponents();
        match = m;
        playerFrame1 = new HumanPlayerFrame(match.getPlayer1());
        playerFrame2 = new ComputerPlayerFrame(match.getPlayer2());
        
        playerFrame1.setMatchFrame(this);
        
        playerFrame1.setVisible(true);
        playerFrame2.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void pon(){
        playerFrame2.pon();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
